basic setup + implement 'eessi init' + add GitHub Actions workflow
EESSI/eessi-cli pull request #1
Opened 2024-06-08 19:02 UTC by boegel

2024-06-08 19:11 UTC, boegel commented
GitHub Actions workflow works fine (see https://github.com/boegel/eessi-cli/actions/runs/9430906635), but is not run yet here because it's not merged yet

2024-06-09 08:54 UTC, bedroge requested changes

2024-06-09 08:54 UTC, bedroge commented on .github/workflows/test.yml
> +      uses: eessi/github-action-eessi@v3.1.0
```suggestion
      uses: eessi/github-action-eessi@e1f8f20638ea417a18d23ab29443ee34794ff900 # v3.1.0
```

2024-06-09 08:54 UTC, bedroge commented on .github/workflows/test.yml
> +    - uses: actions/checkout@v4.1.4
```suggestion
    - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6
```

2024-06-09 08:54 UTC, bedroge commented on .github/workflows/test.yml
> +      uses: actions/setup-python@v4
```suggestion
      uses: actions/setup-python@b64ffcaf5b410884ad320a9cfac8866006a109aa # v4.8.0
```

Or (don't know if there was a specific reason to stick to v4?):
```suggestion
      uses: actions/setup-python@82c7e631bb3cdc910f68e0081d67478d79c6982d # v5.1.0
```

2024-06-09 11:07 UTC, bedroge approved these changes

2024-06-09 11:07 UTC, merged